name: Check Python version 

on:
  workflow_dispatch:

jobs:
  check-python-version:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'      

      - name: Show Python version
        run: python --version
